version: '3.1'

services:
    db_mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: qu3r0S3rDevClick8us=)
            MYSQL_DATABASE: clickbus
        volumes:
            - ./db_mysql_data:/var/lib/mysql
    app:
        build: .
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db_mysql
